# Generated by Django 4.2.16 on 2024-11-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoicedetails_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='invoice',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='invoices.invoices'),
            preserve_default=False,
        ),
    ]
